layout: narrow
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables"]
pygments: true
name: Snakemake example
baseurl : http://website
uploaddir : http://website
ucsc : 
mirror : 