# Specify output directory (path relative to execution directory).
# All other paths in config file are relative to this working directory.
workdir: example/analysis/

# Path to table describing data paths.
data:  ../config/samples.tsv

# Set True if paired sequences provided.
paired: False

# For paired-end stranded set to either - RF or FR
# For single-end stranded set to either - R or F
# For unstranded set to 'unstranded'
strand: R

# Set genome configuration.
genome:
    build: BDGP6
    transcriptome:
        - ../genome/Drosophila_melanogaster.BDGP6.32.cdna.all.fa.gz
        - ../genome/Drosophila_melanogaster.BDGP6.32.ncrna.fa.gz
    index: ../genome/index/BDGP6_tran # Prefix for hisat2 index files
    gff3: ../genome/Drosophila_melanogaster.BDGP6.32.104.gff3.gz

# Cutadapt parameters - see https://cutadapt.readthedocs.io/en/stable/guide.html
cutadapt:
    forwardAdapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
    reverseAdapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
    overlap:        3
    errorRate:      0.1
    minimumLength:  1
    qualityCutoff:  0,0
    GCcontent:      43

misc:
    # Downsample to N reads before alignment. Useful if aligning for QC only.
    # Set to 0 for no downsampling.
    sample:                    0
    # Reduce for example dataset. Not usually required.
    inferExperimentSampleSize: 75000

# Custom configuration file for multiQC.
multiQCconfig: ../config/multiqc_config.yaml

# Configuration file of paths to genome indexes for FastQ Screen.
# See template in example/config/fastqScreen.config.
fastqScreen:

# Set directory for temporary file. Currently unused.
tmpdir: example/analysis/
